# Project information
site_name: 'kakiNote'
site_description: 'kakisoft 個人用メモ'
site_author: 'kakisoft'
site_url: 'https://kakisoft.github.io/MiscellaneousDocs'


# Copyright
# copyright: 'Copyright (c) 2018'

markdown_extensions:
  - admonition
  
# Documentation and theme
docs_dir: 'docs'
theme: 'material'